# Generated by Django 3.1.4 on 2021-01-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20210107_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='todo',
        ),
    ]
